### ISSUE TITLE
Is Priority hop-by-hop?

### ISSUE THREAD

**Issue by LPardue** [kazuho/draft-kazuho-httpbis-priority#2]
The section `Coexistence with HTTP/2 Priorities` makes me wonder if the header should be treated as hop-by-hop, because it relates to the transfer properties of a particular connection. Naively passing through the header in either direction may cause problems?

**Comment by kazuho** [comment]
I think it needs to be end-to-end.

The values transmitted using the Priority field is how the document that affects the client. That property does not change as it traverses through the intermediaries. Therefore end-to-end. The end-to-end nature is also a prerequisite for an intermediary caching and utilizing the value of the header field.

OTOH, how the header is utilized is a hop-by-hop issue. "Coexistence with HTTP/2 Priorities" discusses that, because HTTP/2 can prioritize responses thanks to the streams.

> Naively passing through the header in either direction may cause problems?

I do not think so. The coexistence section states that "an intermediary SHOULD set the settings parameter for a connection it establishes when and only when all the requests to be sent over that connection originates from a client that utilizes this header-based prioritization scheme".

This means that only a HTTP/2 connection that only carries requests from one client (which either uses Priority headers or not) would have the settings parameter set. In such case, a server respects the Priority header of the requests.

When a HTTP/2 connection contains a mix of requests from client sending Priority headers and those do not, the settings parameter is _not_ set, and the server will use the legacy HTTP/2 prioritization scheme.

I think this "respect the header-based priorities only when all the requests on the connection are capable of using it" approach would work fine regardless of the HTTP versions that intermediaries would support.

**Comment by kazuho** [comment]
@LPardue I've created #4 that clarifies my comment above in Considerations. Please let me know what you think.
