### ISSUE TITLE
How to handle unknown urgency parameter values?

### ISSUE THREAD

**Issue by LPardue** [kazuho/draft-kazuho-httpbis-priority#21]
Quoting some text:

> Values of the parameters MUST always be present for the parameters defined in this document. When any of the defined parameters are omitted, or if the Priority header field is not used, their default values SHOULD be applied.

> Unknown parameters MUST be ignored.

IIUC, this covers: unknown parameter name+value (ignore) and name+missing value (error).

What about "known name"+"unknown value"? The reason I ask is that later on we say

> This specification restricts itself to defining just three levels of urgency, in order to provide sufficient granularity for prioritizing responses for ordinary web browsing, at minimal complexity.

> However, that does not mean that the prioritization scheme would forever be stuck to the three levels. The design provides extensibility. If deemed necessary, it would be possible to divide any of the three urgency levels into sub-levels. 

It is foreseeable that an endpoints deploy supports at different rates. So what would happen if a server receives an urgency level it does not understand? Ignoring the parameter would mean the default is assumed? That seems unfortunate for trying to extend priority header, because any deviation results in resources assuming a potential bad default of `document`.

A potential design change here is to rework the default urgency level slightly. For instance we create a mapping of default urgency to content-type (if known by the server), that way omission or unknown urgency level can fallback to a default appropriate to the resource.

**Comment by kazuho** [comment]
> It is foreseeable that an endpoints deploy supports at different rates. So what would happen if a server receives an urgency level it does not understand? Ignoring the parameter would mean the default is assumed? That seems unfortunate for trying to extend priority header, because any deviation results in resources assuming a potential bad default of `document`.

I think we should discourage people from defining new urgency levels. Instead, they should be defining sub-levels. That's what I tried to suggest in section 5.2. Why are there Only Three Levels of Urgency.

That said, I think it might also make sense that unknown urgency levels defaulting to "document" might be a good behavior. This is because I'd assume that place that has the highest probability of seeing a new urgency level would be either above or below "document." If that is the case, endpoints without the knowledge of the extended level defaulting to "document" would make sense.

**Comment by kazuho** [comment]
Regarding having default levels of urgency for each content-type, I am not sure if we want to maintain a registry for that purpose. It is also not always easy, because certain file types could be mapped to different levels. For example, a javascript file could be either blocking or non-blocking, based on how it is used.

Assuming that it would not be easy to find the correct design, I'd prefer deferring the discussion on how to use other signals to Considerations, at least in -00.

**Comment by LPardue** [comment]
I had a different perspective:

Assume the scale is low to high from left to right.

```
non-blocking ------ document ------- blocking
             |                     |
 slightly-non-blocking             blocking-sometimes
```

I define two nonsense levels, their intention is to act close to non-blocking or blocking behaviour; a client can use these level to fine-tune precedence of resources that are similar. A server that defaults back to document is the worst case and tromps over fine tuning. I want to round down to non-blocking or up to blocking but never to document.

I appreciate this is a theoretical exercise. However, there may be different expectations of behavior from people that read this I-D.

**Comment by LPardue** [comment]
> Regarding having default levels of urgency for each content-type, I am not sure if we want to maintain a registry for that purpose. It is also not always easy, because certain file types could be mapped to different levels. For example, a javascript file could be either blocking or non-blocking, based on how it is used.

> Assuming that it would not be easy to find the correct design, I'd prefer deferring the discussion on how to use other signals to Considerations, at least in -00.

WFM, happy to park this

**Comment by kazuho** [comment]
@LPardue Thank you for the examples. I agree that that's probable.

As stated, I think that extensions should define sub-levels, rather than defining a new level. We have a text that recommends that.

At the same time, I agree that we should try to clarify what the server should do when observing an unknown urgency parameter value. Do you have any suggestions on what the default should be?

**Comment by LPardue** [comment]
I think I'm failing to understand the nuance between sub-level and new level. What did you visualise this to be, something like this?

```
non-blocking ------ document ------- blocking
                     /    \
 document-sub-level-1      document-sub-level-2
```
How would that be expressed as a sh-token? Maybe `document/1` and `document/2`?

**Comment by kazuho** [comment]
What I have been trying to suggest in the Considerations is something like below, where `high` and `low` are the values of a different parameter indicating the sub-level. Something like `Priority: urgency=document, importance=high`.

```
non-blocking ------ document ------- blocking
                     /    \
        document-high      document-low
```

**Comment by kazuho** [comment]
If my previous comment makes sense to you, please review #23.

**Comment by LPardue** [comment]
ahhh, now I get it, thanks for you patience

**Comment by kazuho** [comment]
I'm happy that we have caught and fixed an issue in our text. :+1:
