### ISSUE TITLE
Rename "progressive"?

### ISSUE THREAD

**Issue by kazuho** [kazuho/draft-kazuho-httpbis-priority#35]
It might be better to use "interleave".

**Comment by rmarx** [comment]
I feel interleave might be too directly tied to what you expect to happen at bandwidth/scheduling level.

I have personally always preferred "incremental" for this concept.

**Comment by kazuho** [comment]
Thank you for the suggestion. I think I agree that "incremental" is the best option among the three candidates here.

Let's keep this issue open for a while and see what others think.

**Comment by tombergan** [comment]
Abstractly, given two resources A and B, I want to use three kinds of orderings for A and B:

1. Sequential in a specific order (A->B or B->A)
2. Sequential in an unspecified order
3. Interleaved

If A and B are images, we might want to use any of these options:

(1) if A is the hero image
(2) if A and B are the same priority and they are non-progressive images
(3) if A and B are the same priority and they are progressive images

Note that 2 is faster than 3 when the images do not support progressive rendering, because if you fully download one image first, you can draw that first image while the second image is loading.

Another example is async scripts. The order doesn't matter (1 does not make sense) and the scripts cannot be processed incrementally (3 does not make sense). The best option is 2.

The proposal represents 1 with progressive=false and 3 with progressive=true. What should we use for 2? IMO, it's not worth adding another option. It's sufficient to use progressive=true. For example, for images, the client usually does not know a priori whether the images are progressive, therefore it can't decide between 2 and 3. If we spec progressive=true to mean "any order, including interleaved", then the server has the freedom to decide between 2 or 3, once the server learns that the image is (or is not) progressive.

That brings me back to the name. "progressive", "interleaved", and "incremental" all imply (3). Whereas, IMO, the core distinction is really 1 vs (2 and 3). Either the resources must be processed in a specific order, or they can be processed in any order. The name should make that distinction clear. That's why I prefer either:

"sequential", where sequential=true means 1 and sequential=false means (2 or 3)

or

"concurrency", where concurrency=false means 1 and concurrency=true means (2 or 3)

**Comment by kazuho** [comment]
@tombergan Thank you for the suggestion.

> Abstractly, given two resources A and B, I want to use three kinds of orderings for A and B:
> 
> 1. Sequential in a specific order (A->B or B->A)
> 2. Sequential in an unspecified order
> 3. Interleaved
> 
> If A and B are images, we might want to use any of these options:
> 
> (1) if A is the hero image
> (2) if A and B are the same priority and they are non-progressive images
> (3) if A and B are the same priority and they are progressive images
(snip)
> The proposal represents 1 with progressive=false and 3 with progressive=true.

I think we disagree on how the Priority header works.

(1) would be represented by using a different urgency. This is necessary, because the client might want to give higher urgency to a resource that it learns later. The only two options we have within the same urgency group (for non-progressive responses) is to either order them by their stream IDs, or have no order at all. Use of a different urgency level is also necessary for the server, when it promotes the priority of an image above others.

That said, I do agree that we do not have 2 (sequential in an unspecified order). The question is if that would be useful. Assuming that it is something that might benefit us in the future (rather than a signal that we need to have in order to retain comparable performance to the prioritization scheme in H2), I'd prefer doing experiments before arguing for standardization. By moving to a header-field based design, we'd have the room to do such experiments (by using non-standardized parameter names).

I would not respond to the suggestion of the parameter name, because I do not think it would be productive to discuss about the name before reaching consensus on what the name would mean.

**Comment by rmarx** [comment]
I would agree with @kazuho here. 

To me, this proposal takes out (most) of the indicators of how resources interrelate (while the H2 setup focuses on this) and rather just describes how the individual resource is seen by the browser, without implying much about its relations with other resources. As such, the server is free to make those decisions. For this reason, I don't like either "sequential" or "concurrency" and feel "incremental" is best, since it indicates that the browser can process this resource incrementally in a useful way (e.g., I feel browsers might even tag JS files as incremental on mobile if they have a streaming parser/compiler), and NOT explicitly that it therefore should be sent in an interleaved way on the wire.   

Of course, in the case of a "dumb" server, you need default fallback behaviour, which I think is what we're mostly talking about. For that, I don't see that much value in (2) and kind of disagree that for example async script order doesn't matter. While it doesn't matter conceptually, developers will _typically_ list resources in their order of importance in the HTML. As such, the default ordering we propose based on stream ID makes a lot of sense in the "dumb" server case imo. As such, we fall back to just (1) and (3) which the text seems to support just fine. 

I also agree that the server doesn't have enough metadata to really make the 100% correct decision in most cases (e.g., the async scripts). For this, we would need to include much more metadata about the resource, see #28. In the interest of keeping this initial spec simple though, I feel what we have now to be sufficient for the broad strokes.

**Comment by LPardue** [comment]
Flipping the semantic to a "sequential" parameter that defaults to `0` helps to model the default mode of how browsers do things currently (aka reality). In order to deviate from this, the client sends `1`.

cc @nickfajones @schien 

edited to reference previous discussion

**Comment by kazuho** [comment]
> Flipping the semantic to a "sequential" parameter that defaults to `0` helps to model the default mode of how browsers do things currently (aka reality).

Maybe I'm confused, but doesn't Chrome use "sequential=1"? I agree that all other browsers use "sequential=0".

That said, I think that the default should be "sequential=1" (or "incremental=0"). Because all clients would be capable of processing the entire response at once. It is an optional behavior for the clients to make use of the parts of the response as they arrive.

**Comment by rmarx** [comment]
I'm also not entirely following what Lucas is saying above. 

Even though most browsers (sans Chrome) are employing non-sequential as their default, several tests (e.g., our research ,that of @pmeenan) have shown that sequential is overall a *much* better way to go in the default case. As such, it would be sequential=1 that should be the default imo.

With regards to flipping the semantics: I think that could work as well in concept, but not a fan of "sequential", as explained in https://github.com/kazuho/draft-kazuho-httpbis-priority/issues/35#issuecomment-511347872. Other options would be "contiguous", "inseparable", "integral", etc. But none of those sound as approachable/clear as "incremental" imo.

**Comment by c-taylor** [comment]
I'm interested in a parameter that indicates a client preference for sequential delivery. This is present in HTTP1.1 (sort of) and existing h2 priorities scheme. I had understood that "progressive" provided this albeit as a secondary benefit of the parameter and not the main intention.

> "A server SHOULD transmit non-progressive responses one by one, preferably in the order the requests were generated."

...Perhaps this is two distinct signals combined?  "progressive=(0|1)", "sequential"=(0|1)

I think this is just repeating @tombergan

**Comment by kazuho** [comment]
Folks seem to have different rationales behind their preferred names.

OTOH, I think what @rmarx points out (the default behavior should have a value of zero, i.e. false), sound to me like a technical argument.

Is there a technical argument for "sequential"?

If there is not, and if people are not strongly opposed to "incremental", I think it might be a good idea to adopt "incremental" as IMO it is at least better than "progressive".

**Comment by ianswett** [comment]
This is now incremental.

**Comment by LPardue** [comment]
Fixed in #96
