### ISSUE TITLE
Should the priority header be hop-by-hop?

### ISSUE THREAD

**Issue by ianswett** [kazuho/draft-kazuho-httpbis-priority#45]
Making the priority header end-to-end seems like a large departure from HTTP/2 priorities and one I'm not sure we have much/any implementation experience with.  In particular, I know many load balancers and CDNs are still using HTTP 1.1 to backends/application front ends.  In the case of HTTP 1.1, it seems like the intent is to inform the AFE of the request priority and allow overriding it, rather than having the priority apply to the request itself?

It's fairly easy to understand what an implementation should do with a hop-by-hop priority header of this sort, but if a request goes through a load balancer and is proxied to a backend and pooled with other requests, it's not clear to me that the request should be treated as higher priority than the other requests?

One example that sticks out to me is if there was a 'tt'l key in the request header indicating to the server: "Don't bother sending the response after this time", then carrying that to another server would be potentially misleading, since an unknown time would have elapsed between the request being sent and it reaching the second server.  In that case, it seems like the load balancer should make a best effort at adjusting the ttl.

If they are going to remain end-to-end, I think more explanation of what that means is important and a few examples would be helpful.  Currently, most or all of the relevant text is in the "Considerations" section.

**Comment by kazuho** [comment]
@ianswett Thank you for your comments.

> In particular, I know many load balancers and CDNs are still using HTTP 1.1 to backends/application front ends. In the case of HTTP 1.1, it seems like the intent is to inform the AFE of the request priority and allow overriding it, rather than having the priority apply to the request itself?
> 
> It's fairly easy to understand what an implementation should do with a hop-by-hop priority header of this sort, but if a request goes through a load balancer and is proxied to a backend and pooled with other requests, it's not clear to me that the request should be treated as higher priority than the other requests?

I'd argue that a server running behind a proxy can trust and respect the value of the priority header field, as long as the proxy does not coalesce multiple client connections into one. For example, a proxy that converts H3 to H2 (without colaescing) would work totally fine in this respect.

> One example that sticks out to me is if there was a 'tt'l key in the request header indicating to the server: "Don't bother sending the response after this time", then carrying that to another server would be potentially misleading, since an unknown time would have elapsed between the request being sent and it reaching the second server. In that case, it seems like the load balancer should make a best effort at adjusting the ttl.

Actually, my view is that this is a good example for explaining the benefits of an end-to-end header field.

Firstly, the delay you are concerned about is not only introduced within the proxy servers, but also by the packet drops (and retransmissions) that happen on the network. I do not think we need to be too concerned about the delay caused by the proxies. Secondly, I agree that a proxy should adjust the ttl (assuming that it understands that extension). Modification of an end-to-end header field mid-stream is an acceptable behavior. That is an ordinary task for a proxy, for example when handling conditional requests (see [RFC 7234; section 4.3.2](https://tools.ietf.org/html/rfc7234#section-4.3.2)).

Lastly and most importantly, I'd argue that that it helps to inform all the endpoints involved that the response becomes useless in _ttl_ seconds. If the header field is defined as hop-to-hop, then this extension would work only if the proxy that is connected directly to the client recognizes the option. Compared to that, if the header field is defined as end-to-end, it would work if _any_ of the servers understood the option.

I'd reiterate that how a request should be processed and served (regardless of the absolute priority or TTL) is a property of the request, that does not change as it traverses through the intermediaries.

> If they are going to remain end-to-end, I think more explanation of what that means is important and a few examples would be helpful. Currently, most or all of the relevant text is in the "Considerations" section.

Agreed. It would be a good idea to specify how proxies that coalesce connections should act. We could state that such proxies should drop the header field (or add another header field or a directive indicating that the requests have been coalesced from multiple connections).

**Comment by ianswett** [comment]
I'll note this is a duplicate of #2, so readers of this issue should read that one as well.

**Comment by c-taylor** [comment]
In the spirit of 'policy' and discussion that leads to wanting to separate client intent from intermediary intent, can both co-exist?

Client header: End to end policy definition
Server header: End to end policy definition
Frame: Hop by hop application of policy

**Comment by ianswett** [comment]
I think we should close this: TLDR; If you need a hop-by-hop signal, use the frame.  Otherwise, use the header.

**Comment by ianswett** [comment]
Actually, leaving open until I'm sure the draft makes this point clear.

**Comment by rmarx** [comment]
Please discuss further in #99 though.
