### ISSUE TITLE
All urgency values should be available to client and server

### ISSUE THREAD

**Issue by ianswett** [kazuho/draft-kazuho-httpbis-priority#47]
It's fairly non-obvious that some urgency would be client only or server only and some are usable by both.

I tend to think making all of them available to both is best.  As a variation on that, priorities could be defined such that the server's value is slightly higher priority than what the client specifies, for any given value?

If we're going to keep them as is, I'd like a better understanding of why the current asymmetry is very useful.

**Comment by kazuho** [comment]
For supplementary resources, the current scheme is designed to allow two types of intervention from the server-side:
* set the priority above (or below) those used by the client
* reset the priority of a request to normal

The former is useful for serving hero images (or something you do not care at all). The latter is useful for resetting the priority of a hidden image, knowing that you would show it using JavaScript, once the image is being obtained.

The former requires a slot which the clients would not be using, while the latter requires a slot that can be designated by both the client and the server (so that the images in that slot would be interleaved against each other).

Does that make sense to you?

**Comment by rmarx** [comment]
I personally do like the current text/approach: 

> Clients SHOULD NOT use values 1 and 5. Servers MAY use these values to prioritize a response above or below other supplementary responses.

imo, this was one of the issues with the dependency tree, that it was difficult to insert something server-side because you didn't know what the client's intent was. Using this strict ordering and separation between the two, this becomes very clear. Since it's a SHOULD NOT instead of MUST NOT, I feel that still leaves clients with wiggle room for specific use cases. The server is the one sending the data, so it has full access and control, seems logical to me. 

Personally, I would rather increment the range the client can use (e.g., instead of 2-4, to 2-12), but that's a different issue.

**Comment by LPardue** [comment]
IMO we can close this issue, so I'm labelling it as such. Any defenders for keeping it open please speak up.

**Comment by LPardue** [comment]
The discussion was reopened and we landed the change that @ianswett initially suggested. Closing.
