### ISSUE TITLE
'background' priority should suggest changing congestion control to be less aggressive

### ISSUE THREAD

**Issue by ianswett** [kazuho/draft-kazuho-httpbis-priority#48]
The section currently says "As an example, the download of a large file in a web browser would be assigned the background urgency so it would not impact further page loads on the same connection."

Commonly large files are uploaded and downloaded on different connections from the majority of other content for infrastructure reasons.  I believe we should add something like:

"When sending a background request or delivering the response, senders SHOULD change congestion control parameters such as initial congestion window and/or congestion control parameters to be less aggressive in order to ensure higher priority requests are not unnecessarily delayed."

**Comment by kazuho** [comment]
I like the idea of suggesting the use of different congestion-related parameters / algorithms. At the same time, I wonder if it is going to suggest that a different connection should be used for the background urgency? I am not sure if you can have per-stream congestion parameters / algorithms.

**Comment by ianswett** [comment]
Using a separate connection could make things worse, though I think commonly these background request are on separate connections, so it may not change anything.

I'm definitely not recommending per-stream congestion control.  I'm suggesting modifying the connection's congestion control when the highest priority request is 'background'.

It's certainly not possible to change the initial window midway through a connection, so the specific recommendation there would be to consider reducing it when the first request was 'background'.  

On congestion control, it's possible to change the congestion controller on the fly in many OS's(ie: Linux).  Possibly there are some issues if this is done late in the connection, but I've seen this done early in the connection(ie: Use BBR for this experiment group) before.  Alternately, one could modify the CC params to make it less aggressive.  In BBR's case, both TCP and QUIC have a 'drain to target' option that makes BBR drain any queue more frequently, but achieves slightly less bandwidth.  Alternately, one could imagine switching from Cubic to Reno, though neither fixes the bufferbloat issue.

**Comment by LPardue** [comment]
I'm struggling to see what the exact ask is here. Are we attempting to optimise a cross-connection prioritization case without really defining it?

I read the above as "If the maximum priority level in a given connection is `background`, the sender SHOULD reduce the aggressiveness of their congestion control parameters". I don't think that is enough on its own - we would probably need to explain how congestion controllers play with prioritization and then, if we wanted, describe cases like connections that are all `highest`, all `background`, a mix etc. My concern is that the suggestion drives deployments toward sharding, without really understanding why.

**Comment by kazuho** [comment]
@ianswett Thank you for the clarification.

@LPardue I agree that the lack of general guideline is concerning here. At the same time, it is my understanding that we see lots of "background" traffic (e.g., software updates) using distinct connections, and that it is beneficial to provide advice on how they can be less aggressive.

Maybe something like following would be acceptable?

_If possible, a sender SHOULD minimize the impact of less urgent responses delaying other more urgent responses, even when those responses do not share the same connection. As an example, when all the responses being served on a connection are assigned the background urgency, the sender MAY change the congestion control parameters of that connection such as initial congestion window and/or congestion control parameters to be less aggressive, so that more urgent responses being transmitted on other connections are not unnecessarily delayed._

**Comment by LPardue** [comment]
I'm concerned about the attractiveness of gaming the system - if a sender has a high level of confidence that other backgrounded connections will send more slowly, it would look better for its performance to simply ignore this recommendation. Or, for the client to make dummy/no-op higher-priority requests in order to maintain an inflated priority for a connection.

We shouldn't naively ignore the non-functional requirements that consumer-oriented benchmarks have. Are there methods for a receiver to determine the aggresiveness of a congestion control algorithm and counter act?

**Comment by LPardue** [comment]
Some related reading: 

https://github.com/WICG/priority-hints/issues/34

W3C TAG review of priority hints motivated by 

> the possibility that advertisers will say "In order to work with us and serve our ads, you must mark our ads as high priority" -- which really isn't in the interest of the user who was primarily asking to see the content of the page.

**Comment by junhochoi** [comment]
Interesting idea. I was thinking something like LEDBAT. However congestion control applies to a connection. To control individual stream, anything can be done with stream level flow control?

**Comment by LPardue** [comment]
Kicking to the long grass, speak up if you disagree or close the issue if this is no longer desired.
