### ISSUE TITLE
Mixing progressive and non-progressive

### ISSUE THREAD

**Issue by c-taylor** [kazuho/draft-kazuho-httpbis-priority#94]
Un-caffeinated issue:

I can’t see any guidance on the expected behaviour when multiple resources at the same priority level have the progressive attribute set on some resources but not others.

Example (request order):
1: urgency=3 progressive=1
2: urgency=3 progressive=1
3: urgency=3 progressive=1
4: urgency=3 progressive=0
5: urgency=3 progressive=1
6: urgency=3 progressive=1

I presume that {1,2,3} become interleaved, 4 is delivered, {5,6} are interleaved?
This probably requires a few words.

**Comment by rmarx** [comment]
I think for the web browsing use case, it would **probably** make more sense to start sending 4 ASAP before continuing with the progressive resources (i.e., non-progressive resources are more important than progressive ones within the same bucket), though would have to think about this more. 

However, your presumption is also possible and @patmeenan's original proposal (https://github.com/pmeenan/http3-prioritization-proposal/blob/master/README.md) does something different as well (RR between the progressive and non-progressive groups). 

Overall, I would say it's implementation-dependent, BUT I do agree we should include some guidance on what the best "default" behavior would be. This hearkens back to the fact that I feel we should in general have a guidance document on how to optimally use this scheme in practice based on what we've learned from H2. I'll make a new issue to track that as well.

**Comment by kazuho** [comment]
@c-taylor 
> Example (request order):
> 1: urgency=3 progressive=1
> 2: urgency=3 progressive=1
> 3: urgency=3 progressive=1
> 4: urgency=3 progressive=0
> 5: urgency=3 progressive=1
> 6: urgency=3 progressive=1

I presume that {1,2,3} become interleaved, 4 is delivered, {5,6} are interleaved?

Thank you for opening the issue. I think it can be left as implementation-dependent. That said, this is a scheduling problem where once you start serving a non-progressive response, the scheduler should not interleave that response with others.

Based on that observation, I think that something like below would be the best (in sense that it minimizes the deviation from [generalized processor scheduling](https://en.wikipedia.org/wiki/Generalized_processor_sharing), assuming that each request consumes three packets.

123561234445612356

Or, if we consider that the delivery of the succeeding bytes of a progressive response to be less important than others, I think something like 123564441235612356 might be optimal.

All that said, I do not think we need to strictly approximate GPS, and that something similar in spirit would be fine.

**Comment by c-taylor** [comment]
In the example I gave 'my' preference would probably be as I describe, allowing 4 to jump is 'lower priority'. Without a more concrete guidance a few words highlighting the complexity of mixing the attribute is probably 'good enough' although more predictable behaviour is preferred for me here.

IMO RR between the progressive and non-progressive groups would be quite unpredictable in behaviour.

I'd be happy with a warning, as I guess a client could just avoid doing this if it had a preference of a certain behaviour. Perfect would be guidance, others may have stronger views.

---

I want to record this was the first question I was asked when discussing "progressive|interleaved" with a client implementor, so it does perhaps deserve some words. (I was reminded of this when I saw the slides for Thu session of IETF106).

**Comment by kazuho** [comment]
Maybe it's a good idea to expand @c-taylor's case with examples, that explain how the server might end up with having such requests.

One case that I can think of is where a client specifies `priority: u=4, i=?1` for six images. Then, the server sets `priority: i=?0` for the 4th image, because it knows that that image cannot be rendered progressively. Note that the server does not specify the urgency.

In such case, it is my view that the server should interleave the response carrying the five images, and also send the 4th image without interleaving. At the same time, I do _not_ think that the 5th and 6th image should be held back until 1st, 2nd, 3rd images are completely served.

**Comment by kazuho** [comment]
After some time and thought, I now think that the ideal answer would either be 123564441235612356, assuming that the size of each response is known to the H3 terminator when starting to serve the response (e.g., the responses have content-length specified).

Let me explain the rationale.

Our goal is to provide a good representation of a web page as early as possible. From that goal, we can deduct the following observations:
* It is important to serve first few bytes of a response that can be processed incrementally. For example, serving just first 10% of a progressive JPEG image might provide 50% of benefit compared to serving the entire image.
* Conversely, it is not important to serve the last few bytes of a response that can be processed incrementally. As an example, serving last 10% of a progressive JPEG image might only provide 1% additional benefit.
* The only thing that matters for a non-incremental response is the moment the last byte is being served. It does not matter when the first few bytes are served, assuming that the moment the last byte is served does not change. The benefit jumps from 0% to 100% when the last byte is provided.

What we want to do is maximize the sum of the benefits at each moment. But more importantly, the sum of the benefits at earlier moments matters more than the that at later moments (because providing meaningful output to the user ASAP is our key objective).

Based on these observations, looking back at the example, we can now say that the first chunk of an incremental response is more important than the first chunk of a non-incremental response with same urgency. Therefore, the first chunk of 5 and 6 should better be sent prior to that of 4. At the same time, as serving the later portion of an incremental response is less important than serving the final byte of a non-incremental response, the later bytes of 4 should be provided earlier than others. That leads to the conclusion: 123564441235612356.

As stated in my previous comment, I do not think we need to clarify how to solve this issue in the specification. But anyways, this is how I think now.

**Comment by LPardue** [comment]
I think we can close this but deferring to @kazuho

**Comment by kazuho** [comment]
Agreed. Let's close. Priorities are merely hints, we do not define in the specification how a server prioritizes things.
